<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kids - Dress</name>
   <tag></tag>
   <elementGuidId>63815f74-d3b7-4841-8b38-3809c50e3685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kids > div.panel-body > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Kids']/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d5f8743-b67b-45da-bd7c-d1effaa8137e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category_products/4</value>
      <webElementGuid>a12cbfec-e798-4cee-8111-a71d9a8db2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dress </value>
      <webElementGuid>b28117b7-e3f5-4547-a0d8-c285c72d9247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kids&quot;)/div[@class=&quot;panel-body&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>f78d5e42-9e1a-4522-9db2-75bdb98f5197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Kids']/div/ul/li/a</value>
      <webElementGuid>b46125e2-67af-4b77-aa74-c034571fc0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dress')])[2]</value>
      <webElementGuid>6019277f-da13-4da2-bc42-97a781be4d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/following::a[2]</value>
      <webElementGuid>44f7d810-2175-4fad-bfa4-2e9a090722a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops &amp; Shirts'])[1]/preceding::a[1]</value>
      <webElementGuid>a74d9bea-d53e-4f4f-807b-727c60344b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands'])[1]/preceding::a[2]</value>
      <webElementGuid>d1e315bf-ad12-4901-a1c5-8e02a6090c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/category_products/4')]</value>
      <webElementGuid>6a695507-c683-44a1-83c9-62ca551c347e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/ul/li/a</value>
      <webElementGuid>e94d8c60-ad60-4676-a161-0bf9ee17afbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/category_products/4' and (text() = 'Dress ' or . = 'Dress ')]</value>
      <webElementGuid>5a19f2ea-b869-4392-8b30-b866d6baad77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
