<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_addressInfoFrame</name>
   <tag></tag>
   <elementGuidId>7cb7edfa-b3fa-427e-b3f4-91197818d698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5ad31069-b34f-461e-aeea-efc42acf683c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1704689496144</value>
      <webElementGuid>762a9489-3af1-40be-ba29-9e1ba48e355d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressInfoFrame</value>
      <webElementGuid>e7cc332e-eb9a-4447-89a0-8fb776f685a3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
