<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_streetAddress2</name>
   <tag></tag>
   <elementGuidId>760a5a22-9fbd-4976-a142-0ef91977a492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3542c5bc-a968-444c-a573-c516af5d56c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1704689601795</value>
      <webElementGuid>f90bca64-6070-40ad-b0db-a9ea72f777bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ce7667d-e8d7-4240-b19a-76de7b91e97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressLine2</value>
      <webElementGuid>6dc8ea05-5063-4e38-9ad8-db1024150fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/0 iFrame/Home/iFrame Address Info/iframe_addressInfoFrame</value>
      <webElementGuid>0a161dfe-2335-42c4-90af-5299a01663de</webElementGuid>
   </webElementProperties>
</WebElementEntity>
