<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete - Blue Top</name>
   <tag></tag>
   <elementGuidId>b41305ec-08d2-4c3c-b8ae-d5e25f181dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-1 > td.cart_delete > a.cart_quantity_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-1']/td[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3032c525-19f8-4ad7-9466-45056d808342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_quantity_delete</value>
      <webElementGuid>b97ce9dc-7e06-4541-8d20-97d7fa71b8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9c67389-1434-4073-b7a3-0ebd83ed5ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-1&quot;)/td[@class=&quot;cart_delete&quot;]/a[@class=&quot;cart_quantity_delete&quot;]</value>
      <webElementGuid>89191599-abde-4d76-ae63-c8be17fcd01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-1']/td[6]/a</value>
      <webElementGuid>bce39adb-0b69-4e99-b401-74eeb8086e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Top'])[1]/following::a[1]</value>
      <webElementGuid>330db001-2dd5-4ee0-9de7-98740a584cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Tshirt'])[1]/following::a[4]</value>
      <webElementGuid>685fbce4-82fe-4556-80c4-39c209ec8aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::a[1]</value>
      <webElementGuid>7d8f2886-e3dd-4f44-83a9-5da9ef42d193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/preceding::a[1]</value>
      <webElementGuid>bc135b8e-d5c4-4316-bd37-ce7a1aee7e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/a</value>
      <webElementGuid>44f83e19-d43f-41b5-bd9d-feb06cac17c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
