<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_personalInfo</name>
   <tag></tag>
   <elementGuidId>68b1a9c9-875a-4beb-a5d8-a70b9b76fbec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>75a9f47a-6b6d-46af-993d-3d9110c8de55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1704689008715</value>
      <webElementGuid>44174889-a6e5-4a98-b539-fb6371bb0500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personalInfoFrame</value>
      <webElementGuid>1009315f-e21b-4105-92d9-921be7a95aa5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
