<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_firstName</name>
   <tag></tag>
   <elementGuidId>2338d8ad-007d-45d0-9371-0d2d1a322660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>152301257549</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec78e478-aca1-43b6-83d8-85b163b8e996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1704689121310</value>
      <webElementGuid>8d84d067-da75-4cbc-8184-306c64960e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>aa16b902-660c-4caf-a732-2431e05949b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>765ef8dd-ee64-42fa-adc3-ad7754c27992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/0 iFrame/Home/iFrame Personal Info/iframe_personalInfo</value>
      <webElementGuid>51bbfa12-5c25-4f45-9b58-72dc2fcda5f6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
