<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>General - Quantity</name>
   <tag></tag>
   <elementGuidId>4f5c022e-3205-4cbb-bbda-95bc2172cd87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55e8d002-9886-4c26-8ce9-21edf33efde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6a663ad3-6ffb-4f68-8406-2d04ca183b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>bdcba8cb-c4ee-45ba-953f-d9819fa2805e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>70b62b80-ea30-4704-a6d7-2238b1a936e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aeeb262f-294d-4937-952b-1ff12d1128db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d50c70cf-2cb0-44a7-ad0e-9c2f87eec2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity&quot;)</value>
      <webElementGuid>57684d28-90a0-4302-8774-923778303676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity']</value>
      <webElementGuid>dcb4f698-81aa-4d7b-b5ff-80d365219924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5ba044ec-76b7-4c38-8ca7-1e876d40a7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'quantity' and @id = 'quantity']</value>
      <webElementGuid>bdf07c49-1c5f-4c6a-a8dc-2c6c078f9e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
